plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: 
summary: 
lang: en
locale: en_US
url:    "https://johnlaudun.github.io/barebones"
# url: "https://barebones.net"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20